name: BBTweaks
main: me.blvckbytes.bbtweaks.BBTweaksPlugin
version: ${project.version}
author: BlvckBytes
api-version: 1.21
depend: [ItemPredicateParser, WorldGuard]
softdepend: [mcMMO, floodgate]
commands:
  bbtweaks:
    description: 'Administrative base-command of this plugin'
    permission: bbtweaks.command
  uncraft:
    permission: bbtweaks.uncraft
    aliases: [uc]
  getuuid:
    description: 'resolve the UUID of any given name'
    permission: bbtweaks.getuuid
  back:
    description: 'Teleport to a previous location'
    permission: essentials.back
  ping:
    description: 'Get the ping of yourself (and possibly others)'
  mvisualize:
    description: 'Used to visualize multiple nearby magnets simultaneously'
    permission: bbtweaks.mechanic.magnet
  seed:
    description: 'Displays the seed of the current world'
  invfilter:
    description: 'Configure and toggle inventory-filters regarding picked-up items'
    permission: bbtweaks.invfilter
  markers:
    description: 'Browse all available markers'
    permission: bbtweaks.markers
  setmarker:
    description: 'Set a marker to your current location by its name'
    permission: bbtweaks.setmarker
permissions:
  bbtweaks.uncraft.all:
    description: 'Uncraft all available items similar to the one held in one go'
  bbtweaks.ping.other:
    description: 'Access the ping-value of other players'
  bbtweaks.lava-sponge:
    description: 'Use wet sponges to soak up lava and have them be dried'
  bbtweaks.mechanic.clock:
    description: 'Use the clock mechanic'
  bbtweaks.mechanic.pulse-extender:
    description: 'Use the pulse-extender mechanic'
  bbtweaks.mechanic.magnet:
    description: 'Use the magnet mechanic'
  bbtweaks.mechanic.transmitter-receiver:
    description: 'Use the transmitter/receiver mechanic'
  bbtweaks.mechanic.auto-dispose:
    description: 'Use the auto-dispose mechanic'
  bbtweaks.mechanic.sign-flipper:
    description: 'Use the sign-flipper mechanic'
  bbtweaks.markers:
    description: 'Browse all available markers'
  bbtweaks.setmarker:
    description: 'Set a marker to your current location by its name'
