name: BBTweaks
main: me.blvckbytes.bbtweaks.BBTweaksPlugin
version: ${project.version}
author: BlvckBytes
api-version: 1.21
commands:
  bbtweaks:
    permission: bbtweaks.command
  getuuid:
    description: 'resolve the UUID of any given name'
    permission: bbtweaks.getuuid