name: BBTweaks
main: me.blvckbytes.bbtweaks.BBTweaksPlugin
version: ${project.version}
author: BlvckBytes
api-version: 1.21
depend: [ItemPredicateParser, WorldGuard]
softdepend: [mcMMO, floodgate, CraftBook, EssentialsDiscord]
commands:
  bbtweaks:
    description: 'Administrative base-command of this plugin'
    permission: bbtweaks.command
  uncraft:
    permission: bbtweaks.uncraft
    aliases: [uc]
  getuuid:
    description: 'resolve the UUID of any given name'
    permission: bbtweaks.getuuid
  back:
    description: 'Teleport to a previous location'
    permission: essentials.back
  backtrack:
    description: 'Navigate through your history of last-locations'
    permission: essentials.back
  ping:
    description: 'Get the ping of yourself (and possibly others)'
  mvisualize:
    description: 'Used to visualize multiple nearby magnets simultaneously'
    permission: bbtweaks.mechanic.magnet
  seed:
    description: 'Displays the seed of the current world'
  invfilter:
    description: 'Configure and toggle inventory-filters regarding picked-up items'
    permission: bbtweaks.invfilter
  markers:
    description: 'Browse all available markers'
    permission: bbtweaks.markers
  setmarker:
    description: 'Set a marker to your current location by its name'
    permission: bbtweaks.setmarker
  hiddenswitch:
    description: 'Interact with the parameters of a hidden-switch'
    permission: bbtweaks.mechanic.hidden-switch
  password:
    description: 'Respond to password-prompts of the hidden-switch mechanic'
    permission: bbtweaks.mechanic.hidden-switch
  autofly:
    description: 'Toggles automatically enabling essentials'' fly-mode'
  newbieteleport:
    description: 'Teleport to a position within the main world to claim your plot at'
  newbieteleportreset:
    description: 'Resets the newbie-teleport use-count of the given player'
    permission: bbtweaks.newbieteleport.reset
  multibreak:
    description: 'Manages the settings of the multi-break feature'
    permission: bbtweaks.multibreak
  autotool:
    description: 'Toggles the autotool functionality'
    permission: bbtweaks.autotool
permissions:
  bbtweaks.uncraft.all:
    description: 'Uncraft all available items similar to the one held in one go'
  bbtweaks.ping.other:
    description: 'Access the ping-value of other players'
  bbtweaks.lava-sponge:
    description: 'Use wet sponges to soak up lava and have them be dried'
  bbtweaks.mechanic.clock:
    description: 'Use the clock mechanic'
  bbtweaks.mechanic.pulse-extender:
    description: 'Use the pulse-extender mechanic'
  bbtweaks.mechanic.magnet:
    description: 'Use the magnet mechanic'
  bbtweaks.mechanic.transmitter-receiver:
    description: 'Use the transmitter/receiver mechanic'
  bbtweaks.mechanic.auto-dispose:
    description: 'Use the auto-dispose mechanic'
  bbtweaks.mechanic.sign-flipper:
    description: 'Use the sign-flipper mechanic'
  bbtweaks.mechanic.hopper:
    description: 'Use the hopper mechanic'
  bbtweaks.mechanic.hidden-switch:
    description: 'Use the hidden-switch mechanic'
  bbtweaks.markers:
    description: 'Browse all available markers'
  bbtweaks.setmarker:
    description: 'Set a marker to your current location by its name'
  bbtweaks.multibreak.tier.<name>:
    description: 'Give a player access to a named tier of multibreak-limits'
